![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Filtrez les données du dataframe

Nous allons à présent aller un peu plus loin dans la manipulation de nos prêts bancaires. Les demandes suivantes ont été formulées par le responsable du service prêt de notre établissement :
- Le taux d’endettement autorisé est de 35%. Pourriez vous me communiquer le nombre de personnes ayant dépassé ce seuil ?
- Même question, mais cette fois ci uniquement sur l’agence Parisienne
- Pour faciliter le traitement d’éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée `risque` qui nous permettrait d’identifier les clients risqués facilement
- Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers ?
- Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

Vous allez devoir mettre en application l’ensemble des processus de sélection présentés ci-dessus pour répondre à ces différentes demandes.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# traitement réalisés précédemment
prets = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/prets.csv')

# calcul du taux d'endettement
prets['taux_endettement'] = round(prets['remboursement'] * 100 / prets['revenu'], 2)

# renommer taux en taux_interet
prets.rename(columns={'taux':'taux_interet'}, inplace=True)

# calculer le cout total du pret
prets['cout_total'] = prets['remboursement'] * prets['duree']

# calculer les bénéfices mensuels réalisés
prets['benefices'] = round((prets['cout_total'] * prets['taux_interet']/100)/(24), 2)

prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57

Le taux d’endettement autorisé est de 35%. Pourriez vous me communiquer le nombre de personnes ayant dépassé ce seuil ? vous pourrez me stocker la liste dans une variable à part nommé `clients_risque`

In [5]:
clients_risque = prets.loc[prets['taux_endettement'] > 35, :]
clients_risque.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices
7,6,LYON,69008,1867.0,711.33,240,immobilier,1.196,38.1,170719.2,85.08
8,7,NICE,6000,5486.0,2956.95,300,immobilier,1.184,53.9,887085.0,437.63
10,9,MARSEILLE,13012,1386.0,612.61,180,immobilier,1.284,44.2,110269.8,58.99
15,14,TOULOUSE,31400,2413.0,1334.39,300,immobilier,1.154,55.3,400317.0,192.49
21,20,LYON,69001,3318.0,1237.61,240,immobilier,1.148,37.3,297026.4,142.08

Même question, mais cette fois ci uniquement sur l’agence Parisienne

In [8]:
clients_risque_paris = prets.loc[(prets['taux_endettement'] > 35) & (prets['ville'] == 'PARIS'), :]
clients_risque_paris.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices
70,67,PARIS,75014,5598.0,2395.94,240,immobilier,1.136,42.8,575025.6,272.18
75,72,PARIS,75012,5981.0,2230.91,240,immobilier,1.150,37.3,535418.4,256.55
89,85,PARIS,75005,6341.0,2980.27,240,immobilier,1.074,47.0,715264.8,320.08
129,122,PARIS,75001,6536.0,2457.54,120,immobilier,1.038,37.6,294904.8,127.55
143,134,PARIS,75003,2870.0,1021.72,180,immobilier,1.104,35.6,183909.6,84.60

Pour faciliter le traitement d’éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée `risque` qui aurait pour valeur `Oui` si le client est risqué (taux d’endettement > 35%), `Non` sinon.
Pour se faire, je vous conseille de créer la variable `risque` en l'initialisant à `Non` (ou `Oui`, à votre préférence) et de ne modifier que les lignes concernées par la valeur inverse :

In [12]:
prets['risque'] = "Non"
prets.loc[prets['taux_endettement'] > 35, 'risque'] = "Oui"

prets.sample(5)

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices,risque
189,176,PARIS,75008,4605.0,1132.83,240,immobilier,1.256,24.60,271879.2,142.28,Non
202,189,TOULOUSE,31500,1529.0,461.76,300,immobilier,1.175,30.20,138528.0,67.82,Non
154,144,MARSEILLE,13010,2240.0,316.60,81,automobile,3.267,14.13,25644.6,34.91,Non
70,67,PARIS,75014,5598.0,2395.94,240,immobilier,1.136,42.80,575025.6,272.18,Oui
33,32,BORDEAUX,33200,3419.0,1196.65,180,immobilier,1.222,35.00,215397.0,109.67,Non

Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers ?

In [30]:
prets_auto = prets.loc[prets['type'] == "automobile", 'cout_total'].values

print("Le coût total moyen des prêts automobiles est de", prets_auto.mean(), "€")

Le coût total moyen des prêts automobiles est de 13665.0 €

Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

In [35]:
benef_mensuel = prets.loc[prets['ville'] == 'TOULOUSE', 'benefices']

print("Le bénéfice mensuel total réalisé par l'agence Toulousaine est de", round(benef_mensuel.sum(), 2), "€")

Le bénéfice mensuel total réalisé par l'agence Toulousaine est de 2138.07 €

Félicitation ! Je vous invite fortement à vérifier vos réponses avec [la correction ci contre](https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P2/P2C3%20-%20Filtrez%20les%20donn%C3%A9es%20du%20data%20frame%20-%20correction.ipynb).